### ISSUE TITLE
fatal error: 'sensors/sensors.h' file not found when using LMSENSORS_INCLUDE_DIR

### ISSUE THREAD

**Issue by wiiznokes** [koutheir/sensors-sys#1]
I want to generate binding from [this version](https://github.com/Wer-Wolf/lm-sensors/tree/pwm)  of lm-sensors to get PWM support (i know i will need to fork [lm-sensors](https://github.com/koutheir/lm-sensors)), 
but i get an error when compiling this crate.

This is the env vars i set:

```shell
$ export LMSENSORS_INCLUDE_DIR=/home/lenaic/Documents/fan-control-rs/lib/include/
$ export LMSENSORS_LIB_DIR=/home/lenaic/Documents/fan-control-rs/lib/lib
$ export LMSENSORS_STATIC=1
```

`sensors-sys` take them into account, i added a `dbg!(&include_dir);` in the `build.rs` file to be sure, and this is what is show:
```
 [/home/lenaic/Documents/sensors-sys/build.rs:80] &include_dir = Some(
      "/home/lenaic/Documents/fan-control-rs/lib/include/",
  )
```

Include files are here, libs too. 
```
$ ls /home/lenaic/Documents/fan-control-rs/lib/include/sensors/
error.h  sensors.h
```

And this is the error:
```
  /home/lenaic/Documents/sensors-sys/sensors-sys.h:2:10: fatal error: 'sensors/sensors.h' file not found
  thread 'main' panicked at /home/lenaic/Documents/sensors-sys/build.rs:371:39:
  sensors-sys: Failed to generate Rust bindings for 'sensors/sensors.h' and other headers: ClangDiagnostic("/home/lenaic/Documents/sensors-sys/sensors-sys.h:2:10: fatal error: 'sensors/sensors.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Is it possible that `builder.generate()` have no access to ENV var?

https://github.com/koutheir/sensors-sys/blob/9aba1a0f26d4ce20ae43a3789117a1b25f99a497/build.rs#L370

**Comment by wiiznokes** [comment]
After looking a bit more at the code, it seems that include and lib dir are found but not used:

```rust
find_and_output_include_dir(&compiler_search_paths.include_paths, docs_only_mode);

    find_and_output_lib_dir(
        &compiler_search_paths.link_paths,
        &target,
        explicit_static,
        docs_only_mode,
    );

    generate_bindings(
        &out_dir,
        if docs_only_mode {
            HEADER_DOCS_RS
        } else {
            HEADER
        },
    )
```

The result of both find function is not used. I think this is a bug

**Comment by wiiznokes** [comment]
I fix it that way:
- get the include path from `find_and_output_include_dir`
- pass it to `generate_bindings`
- add this line to the builder: `.clang_arg(format!("-I/{}", include_path.to_string_lossy()));`

I would be happy to PR that but i'm not sure about the fix

**Comment by koutheir** [comment]
Good catch! And thank you for your analysis.

Please update to `sensors-sys` version `0.2.10` and let me know if it fixes the issue you discovered.

**Comment by wiiznokes** [comment]
I can confirm it work now, thanks
